# Generated by Django 2.2.6 on 2020-03-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
    ]
